//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace grocery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tableBanner
    {
        public int bannerId { get; set; }
        public string bannerName { get; set; }
        public string bannerDescription { get; set; }
        public string photo { get; set; }
    }
}
