//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace grocery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOrder()
        {
            this.tblOrderDetails = new HashSet<tblOrderDetail>();
        }
    
        public int OrderId { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Aadress { get; set; }
        public string Phone { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> OrderTime { get; set; }
        public string DeliveredStatus { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
    
        public virtual tblOrder tblOrder1 { get; set; }
        public virtual tblOrder tblOrder2 { get; set; }
        public virtual tblOrder tblOrder11 { get; set; }
        public virtual tblOrder tblOrder3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblOrderDetail> tblOrderDetails { get; set; }
    }
}
